### ISSUE TITLE
Please support null safety

### ISSUE THREAD

**Issue by HamzaMihfad** [hiranthaR/string_to_color#1]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:string_to_color

**Comment by talamaska** [comment]
@hiranthaR You have merged the PR fixing this issue, but you haven't published the v2. Could you please find time to publish it?

**Comment by hiranthaR** [comment]
> @hiranthaR You have merged the PR fixing this issue, but you haven't published the v2. Could you please find time to publish it?

@talamaska I published the code. please check now

**Comment by talamaska** [comment]
thanks
